resources:
- repo: self
  clean: true

trigger:
  - master

variables:
  moduleName: 'UKHO.ADM'
  repositoryPublishUri: https://proget.ukho.gov.uk/nuget/ukho.psgallery/Packages
  repositorySourceUri: https://proget.ukho.gov.uk/nuget/ukho.psgallery

queue:
  name: NautilusBuild
#Your build pipeline references an undefined variable named ‘NugetAPIKey’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972

steps:
- powershell: |
    ./Build/Build.ps1 `
      -ManifestFilePath $(Build.SourcesDirectory)\$(moduleName)\$(moduleName).psd1 `
      -PreReleaseTag dev$(Build.BuildId) `
      -Branch $(Build.SourceBranchName) 
  displayName: Build package $(moduleName)

# By default writes the results of  the tests to an NUnit XML file at $(Build.SourcesDirectory)\Test-Pester.XML
- powershell: '$(Build.SourcesDirectory)\UKHO.ADM.Tests\Run-Tests.ps1 `
              -ManifestFilePath $(Build.SourcesDirectory)\$(moduleName)\$(moduleName).psd1'
  displayName: Run Pester Tests
        


 
# Publish the NUnit XML
- task: PublishTestResults@2
  displayName: Publish Test Results
  inputs:
    testResultsFormat: NUnit
    testResultsFiles: '$(Build.SourcesDirectory)\Test-Pester.XML'
    mergeTestResults: true
    testRunTitle: '$(Build.DefinitionName) Pester Tests'

- powershell: | 
    ./Deploy/DeployToFeed.ps1 -RepositoryName $(RepositoryName) -RepositorySourceUri $(RepositorySourceUri) -RepositoryPublishUri $(RepositoryPublishUri) -NugetAPIKey $(NugetApiKey) -ModuleFolderPath $(Build.SourcesDirectory)\UKHO.ADM
  displayName: 'Publish module to feed'