resources:
- repo: self
  clean: true

trigger:
  branches:
    include:
      - refs/heads/*

queue:
  name: NautilusBuild
#Your build pipeline references an undefined variable named ‘NugetAPIKey’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972

steps:
# By default writes the results of  the tests to an NUnit XML file at $(Build.SourcesDirectory)\Test-Pester.XML
- task: richardfennellBM.BM-VSTS-PesterRunner-Task.Pester-Task.Pester@6
  displayName: Run Pester Tests
  inputs:
    scriptFolder: '$(Build.SourcesDirectory)\UKHO.ADM.Tests\Run-Tests.ps1'
 
# Publish the NUnit XML
- task: PublishTestResults@2
  displayName: Publish Test Results
  inputs:
    testResultsFormat: NUnit
    testResultsFiles: '$(Build.SourcesDirectory)\Test-Pester.XML'
    mergeTestResults: true
    testRunTitle: '$(Build.DefinitionName) Pester Tests'
- powershell: |
    ./Build/Import-RequiredModules.ps1 -ManifestFilePath "$(Build.SourcesDirectory)\UKHO.ADM\UKHO.ADM.psd1"
  displayName: Makes sure required modules are installed on server where tests are run.

- powershell: |
    ./Build/Add-FunctionsToExport.ps1 -ManifestFilePath "$(Build.SourcesDirectory)\UKHO.ADM\UKHO.ADM.psd1"
  displayName: Add public funtions to be exported

- powershell: | 
    ./Build/Set-ModuleAsPreRelease.ps1 -PreReleaseTag "dev$(Build.BuildId)" -ManifestFilePath "$(Build.SourcesDirectory)\UKHO.ADM\UKHO.ADM.psd1" -Branch $(Build.SourceBranchName)
  displayName: Set module as PreRelease if branch is not master

- powershell: | 
    ./Deploy/DeployToFeed.ps1 -RepositoryName $(RepositoryName) -RepositorySourceUri $(RepositorySourceUri) -RepositoryPublishUri $(RepositoryPublishUri) -NugetAPIKey $(NugetApiKey) -ModuleFolderPath $(Build.SourcesDirectory)\UKHO.ADM
  displayName: 'Publish module to feed'